name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Install Puppeteer Chromium
        run: npx puppeteer browsers install chrome

      - name: Build Windows
        run: npm run build:win

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/KursMax-WhatsApp-Setup-${{ github.ref_name }}.exe
            dist/latest.yml
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  mac-release:
    runs-on: macos-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Install Puppeteer Chromium
        run: npx puppeteer browsers install chrome

      - name: Build Mac
        run: npm run build:mac

      - name: Upload Mac Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/KursMax-WhatsApp-${{ github.ref_name }}-arm64.zip
            dist/latest-mac.yml
          draft: false
          prerelease: false
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
